### ISSUE TITLE
Build Error 6.3

### ISSUE THREAD

**Issue by ptsequeira** [hansemannn/titanium-firebase-crash-reporting#1]
Hi @hansemannn,

When i include the **Crash Reporting Module** the application fails to build with the following error:

`** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	PhaseScriptExecution Run\ Script build/Intermediates/FirebaseTestApp.build/Debug-iphonesimulator/FirebaseTestApp.build/Script-000000000000000000000027.sh`

I'm using 6.3.0 GA

Thanks!

**Comment by hansemannn** [comment]
Make sure to adjust the path to your script correctly. Configuring this module is a bit advanced but brings huge benefits by being able to upload crash-reports automatically. 

In detail, the [module hook](https://github.com/hansemannn/titanium-firebase-crash-reporting/blob/master/ios/hooks/hook-run-script-phase.js) expects a file called `titanium-firebase-script.sh` in `<project-root>/scripts` that calls the Firebase scripts (also placed there and available in this repo) like documented in the Firebase docs.

An example of this file:
```bash
#!/bin/bash

# Replace this with the GOOGLE_APP_ID from your GoogleService-Info.plist file
GOOGLE_APP_ID=1:my:app:id

# Replace the /Path/To/ServiceAccount.json with the path to the key you just downloaded
"../../scripts/upload-sym "/Path/To/ServiceAccount.json"
```

Once the keys are set properly, it will invoke the `upload-sym` script with your `ServiceAccount.json` as the parameter and `GOOGLE_APP_ID` as an env-variable. I will try to document this in the readme in the future, but I haven't had the time so far.
