### ISSUE TITLE
JS exceptions?

### ISSUE THREAD

**Issue by AppWerft** [hansemannn/titanium-firebase-crash-reporting#5]
Hi Hans,
I see in your module you simple switch on and off the crash reporter. But what happens, if the KrollException happens. I thinkthis is a JS only issue and will not send to server. Or is it a mistake?
In Sentry module I have added this https://github.com/AppWerft/Ti.Sentry/blob/master/android/src/ti/sentry/SentryModule.java#L86 will say I have registered an additional handler

**Comment by hansemannn** [comment]
It's usually started during app launch and then catches all exceptions occurring, so no additional setup is required. If you are having issues catching exceptions, let me know!
